# Generated by Django 5.1.3 on 2025-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="problem_title",
            field=models.TextField(default="="),
            preserve_default=False,
        ),
    ]
