# Generated by Django 5.1.3 on 2025-01-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_usersubmission_feedback_usersubmission_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubmission",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="score",
        ),
    ]
