# Generated by Django 4.2.19 on 2025-02-16 11:44

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_uploadedfile_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='judgment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=base.models.UploadedFile.get_upload_path),
        ),
    ]
