# Generated by Django 4.2.19 on 2025-02-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_usersubmission_status_judgment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='judge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.customuser'),
            preserve_default=False,
        ),
    ]
