# Generated by Django 4.2.19 on 2025-02-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_judgment_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customuser')),
                ('user_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.usersubmission')),
            ],
        ),
    ]
